name: .NET

on: [push]

env:
  DOTNET_SDK_VERSION: '6.0.100-rc.2.21430.7'
  INCLUDE_PRERELEASE: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
        include-prerelease: ${{ env.INCLUDE_PRERELEASE }}
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.5
    - name: Install TypeScript and typedoc
      run: sudo npm install -g typescript@4.2.* typedoc@0.20.*
    - name: Build with dotnet
      run: dotnet build
    - name: Test with dotnet
      run: dotnet test
  
  publish-native-windows:
    runs-on: windows-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
        include-prerelease: ${{ env.INCLUDE_PRERELEASE }}
    - name: Publish Native Windows x64 Release
      run: |
        dotnet publish NugetCleaner -c Release -r win-x64 -o WindowsNativeBuildx64
        del WindowsNativeBuildx64\*.pdb
    - name: Upload Windows x64 native artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Windows_x64_Native
        path: WindowsNativeBuildx64
    - name: Publish Native Windows ARM64 Release
      run: |
        dotnet publish NugetCleaner -c Release -r win-arm64 -o WindowsNativeBuildARM64
        del WindowsNativeBuildARM64\*.pdb
    - name: Upload Windows ARM64 native artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Windows_ARM64_Native
        path: WindowsNativeBuildARM64

  publish-native-linux:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
        include-prerelease: ${{ env.INCLUDE_PRERELEASE }}
    - name: Install Kerberos 5 library
      run: |
        sudo apt update
        sudo apt install -y libkrb5-dev
    - name: Publish Native Linux x64 Release
      run: |
        dotnet publish NugetCleaner -c Release -r linux-x64 -o LinuxNativeBuildx64
        rm LinuxNativeBuildx64/*.pdb
        strip LinuxNativeBuildx64/NugetCleaner
    - name: Upload Linux x64 native artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Linux_x64_Native
        path: LinuxNativeBuildx64
  
  public-native-linux-arm64:
    runs-on: ubuntu-latest
    needs: build-and-test
    container: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-cross-arm64-20201022204150-b2c2436

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
        include-prerelease: ${{ env.INCLUDE_PRERELEASE }}
    - name: Publish Native Linux ARM64 Release
      run: |
        dotnet publish NugetCleaner -c Release -r linux-arm64 -o LinuxNativeBuildARM64 /p:CppCompilerAndLinker=clang-9 /p:SysRoot=/crossrootfs/arm64
        rm LinuxNativeBuildARM64/*.pdb
        aarch64-linux-gnu-strip LinuxNativeBuildARM64/NugetCleaner
    - name: Upload Linux ARM64 native artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Linux_ARM64_Native
        path: LinuxNativeBuildARM64

  publish-native-macos:
    runs-on: macos-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
        include-prerelease: ${{ env.INCLUDE_PRERELEASE }}
    - name: Publish Native macOS x64 Release
      run: |
        dotnet publish NugetCleaner -c Release -r osx-x64 -o macOSNativeBuildx64
        rm macOSNativeBuildx64/*.pdb
        strip macOSNativeBuildx64/NugetCleaner
    - name: Upload macOS x64 native artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: macOS_x64_Native
        path: macOSNativeBuildx64
